#!/bin/sh
WHITE="\033[0;0m"
GRAY="\033[37;5m"
RED="\033[0;31m"
GREEN="\033[0;32m"
ORANGE="\033[0;33m"
BLUE="\033[0;34m"
PURPLE="\033[0;35m"

clear

echo -e "
$GRAY   +---------------------------+
$GRAY   |                           |
$GRAY   |            $BLUE$USER$WHITE@$RED$HOSTNAME
$GRAY   |$WHITE    (\,/)   $GREEN$(uname) $(uname -m)
$GRAY   |$WHITE   (. . )   $PURPLE$(uname -r)
$GRAY   |$WHITE  (+)~(+)o  $BLUE$XDG_CURRENT_DESKTOP
$GRAY   |                           |
$GRAY   +---------------------------+
$GRAY   |$WHITE  Mem: $ORANGE$(free -h --giga | grep "Mem:" | cut -d " " -f 22)$WHITE/$RED$(free -h --giga | grep "Mem:" | cut -d " " -f 14)
$GRAY   |$WHITE  Pac: $GREEN$(pacman -Q | wc -l)
$GRAY   +---------------------------+
"

for i in $(seq 3 10)
do
    tput cup $i 31
    if [ $i -eq 8 ]; then
        echo -e "$GRAY+"
    else
        echo -e "$GRAY|"
    fi
done

tput cup 12 0  && echo -e "$WHITE"
