#!/bin/sh

dt=$(date +'%Y%m%d%H%M%S'"_print.png")

if [[ "$1" == "-s" ]]; then
    grim -g "$(slurp)" ~/Pictures/Prints/$dt; sleep 0.01; wl-copy < ~/Pictures/Prints/$dt
else
    grim ~/Pictures/Prints/$dt; sleep 0.01; wl-copy < ~/Pictures/Prints/$dt
fi
